export const topCollections = [
    {
        name: 'Bored Ape Yacht Club',
        symbol: "BAYC",
        contract: "0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d",
        icon: "/community/bayc-icon.png",
        banner: "/community/bayc-banner.png",
        bg: "/community/bayc-bg.png",
    },
    {
        name: 'Azuki',
        symbol: 'Azuki',
        contract: "0xed5af388653567af2f388e6224dc7c4b3241c544",
        icon: "/community/azuki-icon.png",
        banner: "/community/azuki-banner.png",
        bg: "/community/azuki-bg.png",
    },
    {
        name: 'mfers',
        symbol: 'mfer',
        contract: "0x79fcdef22feed20eddacbb2587640e45491b757f",
        icon: "/community/mfers-icon.png",
        banner: "/community/mfers-banner.png",
        bg: "/community/mfers-bg.png",
    },
    {
        name: "Moonbirds",
        symbol: 'Moonbird',
        contract: "0x23581767a106ae21c074b2276d25e5c3e136a68b",
        icon: "/community/moonbirds-icon.png",
        banner: "/community/moonbirds-banner.png",
        bg: "/community/moonbirds-bg.png",
    },
    {
        name: "Crypto Coven",
        icon: "/community/cryptocoven-icon.png",
        banner: "/community/cryptocoven-banner.png",
        contract: "0x5180db8f5c931aae63c74266b211f580155ecac8",
        symbol: "WITCH",
        bg: "/community/cryptocoven-bg.png"
    },
    // {
    //     name: 'mferspet',
    //     symbol: 'mferspet',
    //     contract: "0xb51fec702a259759690ab0e8648033d18ef099c1",
    //     icon: "/community/bayc-icon.png",
    //     banner: "/community/bayc-banner.png",
    //     bg: "/community/bayc-bg.png", icon: "/community/bayc-icon.png",
    //     banner: "/community/bayc-banner.png",
    //     bg: "/community/bayc-bg.png",
    // },
    {
        name: 'goblintown.wtf',
        symbol: 'goblintown',
        contract: "0xbce3781ae7ca1a5e050bd9c4c77369867ebc307e",
        icon: "/community/goblintown-icon.png",
        banner: "/community/goblintown-banner.png",
        bg: "/community/goblintown-bg.png",
    },
    {
        name: 'Doodles',
        symbol: 'Doodle',
        contract: "0x8a90cab2b38dba80c64b7734e58ee1db38b8992e",
        icon: "/community/doodles-icon.png",
        banner: "/community/doodles-banner.png",
        bg: "/community/doodles-bg.png",
    },
    {
        name: 'Boki',
        symbol: 'Boki',
        contract: "0x248139afb8d3a2e16154fbe4fb528a3a214fd8e7",
        icon: "/community/boki-icon.png",
        banner: "/community/boki-banner.png",
        bg: "/community/boki-bg.png",
    },
    {
        name: 'Meebits',
        symbol: 'Meebit',
        contract: "0x7bd29408f11d2bfc23c34f18275bbf23bb716bc7",
        icon: "/community/meebits-icon.png",
        banner: "/community/meebits-banner.png",
        bg: "/community/meebits-banner.png",
    },
    {
        name: 'DEGEN TOONZ COLLECTION',
        symbol: "TOONZ",
        contract: "0x19b86299c21505cdf59ce63740b240a9c822b5e4",
        icon: "/community/toonz-icon.png",
        banner: "/community/toonz-banner.png",
        bg: "/community/toonz-bg.png",
    },
]

export type Collection = {
    name: string,
    symbol: string,
    contract: string,
    icon: string,
    bg: string,
    banner: string,
}